version: "3"
services:
  easy_web_js:
    build: .
    image: gkirito/easy_browser
    restart: always
    ports:
      - "8084:8000"
    environment:
      - FLAG=flag{8b68f1c6-e4c2-435d-90cf-23667bb79dc0}
